### ISSUE TITLE
(SERVER CRASH) Crash on Lost Souls spawn

### ISSUE THREAD

**Issue by Vaygrim** [McJty/LostSouls#4] opened 2018-02-26 19:59 UTC
In v0.6.2 of "GrimCo's Wasted" (using Lost Souls 1.12-1.1.4) we are getting a pretty consistent crash when Lost Souls entities spawn in. Can replicate fairly easily, let me know if this is an issue with WHAT we're spawning in (in which case it's a TechGuns 2 problem) or if it's actually a Lost Souls issue? Thanks!

[crash-2018-02-26_03.44.48-server.txt](https://github.com/McJty/LostSouls/files/1760108/crash-2018-02-26_03.44.48-server.txt)

[crash-2018-02-26_03.47.13-server.txt](https://github.com/McJty/LostSouls/files/1760109/crash-2018-02-26_03.47.13-server.txt)

**Comment by McJty** [comment] 2018-02-26 20:11
I will check it out tomorrow

**Comment by McJty** [comment] 2018-02-27 04:48
Closing this because it was apparently caused by a wrong techguns mob

**Closed by McJty** 2018-02-27 04:48 UTC
